import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';

const jost = Jost({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-jost', // Add this back
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${jost.variable} ${jost.className}`}>
      <head>
        <meta name='viewport' content='initial-scale=1, width=device-width' />
      </head>
      <body className='antialiased'>
        <div className='flex h-screen flex-col'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
